name: Kanlaya #ชื่อที่ show บน github

on: 
  workflow_dispatch:

env:
  myname: Thailand

jobs:
  echo:
    runs-on: app1
    steps:
      - name: itmyname
        run: |
          echo "Hello Kanlaya from ${{ env.myname }}"
          ls -la
          pwd